var initDataTable = {//初始化表格数据
  "00": [
  {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_ID",
    "C_LENGTH": "20",
    "C_IS_NULL": false,
    "C_COMMENT": "主键ID",
    "C_PRIMARY": true,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_CREATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar",
    "C_COLUMN": "C_CREATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_UPDATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar",
    "C_COLUMN": "C_UPDATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "datetime",
    "C_COLUMN": "C_CREATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": false,
    "C_COMMENT": "创建时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "datetime",
    "C_COLUMN": "C_UPDATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": true,
    "C_COMMENT": "修改时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }
],
  "01": [
  {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_ID",
    "C_LENGTH": "20",
    "C_IS_NULL": false,
    "C_COMMENT": "主键ID",
    "C_PRIMARY": true,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_PARENT_ID",
    "C_LENGTH": "20",
    "C_IS_NULL": false,
    "C_COMMENT": "父ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar",
    "C_COLUMN": "C_TEXT",
    "C_LENGTH": "100",
    "C_IS_NULL": false,
    "C_COMMENT": "树label",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar",
    "C_COLUMN": "C_CASCADE",
    "C_LENGTH": "200",
    "C_IS_NULL": false,
    "C_COMMENT": "级联关系",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_CREATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar",
    "C_COLUMN": "C_CREATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "bigint",
    "C_COLUMN": "C_UPDATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar",
    "C_COLUMN": "C_UPDATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "datetime",
    "C_COLUMN": "C_CREATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": false,
    "C_COMMENT": "创建时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "datetime",
    "C_COLUMN": "C_UPDATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": true,
    "C_COMMENT": "修改时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }
],
  "02": [
  {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_ID",
    "C_LENGTH": "20",
    "C_IS_NULL": false,
    "C_COMMENT": "主键ID",
    "C_PRIMARY": true,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_CREATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar2",
    "C_COLUMN": "C_CREATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_UPDATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar2",
    "C_COLUMN": "C_UPDATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "date",
    "C_COLUMN": "C_CREATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": false,
    "C_COMMENT": "创建时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "date",
    "C_COLUMN": "C_UPDATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": true,
    "C_COMMENT": "修改时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }
],
  "03": [
  {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_ID",
    "C_LENGTH": "20",
    "C_IS_NULL": false,
    "C_COMMENT": "主键ID",
    "C_PRIMARY": true,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_PARENT_ID",
    "C_LENGTH": "20",
    "C_IS_NULL": false,
    "C_COMMENT": "父ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar2",
    "C_COLUMN": "C_TEXT",
    "C_LENGTH": "100",
    "C_IS_NULL": false,
    "C_COMMENT": "树label",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar2",
    "C_COLUMN": "C_CASCADE",
    "C_LENGTH": "200",
    "C_IS_NULL": false,
    "C_COMMENT": "级联关系",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_CREATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar2",
    "C_COLUMN": "C_CREATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": false,
    "C_COMMENT": "创建者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "number",
    "C_COLUMN": "C_UPDATE_BY",
    "C_LENGTH": "9",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者ID",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "varchar2",
    "C_COLUMN": "C_UPDATOR",
    "C_LENGTH": "50",
    "C_IS_NULL": true,
    "C_COMMENT": "更新者",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "date",
    "C_COLUMN": "C_CREATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": false,
    "C_COMMENT": "创建时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }, {
    "C_COLUMN_TYPE": "date",
    "C_COLUMN": "C_UPDATE_TIME",
    "C_LENGTH": "",
    "C_IS_NULL": true,
    "C_COMMENT": "修改时间",
    "C_PRIMARY": false,
    "C_DEFAULT": true
  }
]
}

export {
  initDataTable
}
